### ISSUE TITLE
Licensing confusion

### ISSUE THREAD

**Issue by sethwoodworth** [buckmaxwell/zippy#13]
On PyPi it says that the library is free for non-commercial use, but requires a license for commercial use.  And at the same time your `setup.py` says the license is MIT.

Which is correct?

**Comment by buckmaxwell** [comment]
Free for non-commercial use (but I'm not the person you pay).  Unfortunately there is now a dependency on a dataset that should be paid for as per the readme. That's as of 3.X.X -- versions before that don't have any paid dependency, but likely will be missing zipcodes.

Since the dataset IS packaged with zipcode, I can change the license. Sorry for confusion.

**Comment by sethwoodworth** [comment]
Thank you for the clarification.  That makes total sense now.  Thank you!  (and I may be licensing)

**Comment by buckmaxwell** [comment]
@sethwoodworth  - pushed v4 just now, it's on pypi and here.  v4 no longer packages the data, only supplies instructions for downloading it and building the database (now in any RDBMS or Sqlite you wish).  This should alleviate licensing confusion as the full repo is truly MIT now that there is no longer the data packed with it.
